version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: intera_libra_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: intera_libra
    ports:
      - "5432:5432"
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
