server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: alfabetizalibras-server
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/alfabetizalibras}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET:c3VwZXItc2VjcmV0LWp3dC1rZXktZm9yLWFsZmFiZXRpemFsaWJyYXMtYXBwbGljYXRpb24tc2VjdXJpdHk=}
  expiration: ${JWT_EXPIRATION:86400000} # 24 horas

minio:
  url: ${MINIO_URL:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
  bucketName: ${MINIO_BUCKET_NAME:alfabetizalibras}
