server:
  port: 8081

spring:
  application:
    name: alfabetizalibras-server
  datasource:
    url: jdbc:postgresql://localhost:5432/alfabetizalibras
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: c3VwZXItc2VjcmV0LWp3dC1rZXktZm9yLWFsZmFiZXRpemFsaWJyYXMtYXBwbGljYXRpb24tc2VjdXJpdHk=
  expiration: 86400000 # 24 horas

minio:
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: alfabetizalibras
